= Multi-tenancy best practices
:toc: true
:toclevels: 2

:page-title: Multi-tenancy best practices
:page-pageid: multi-tenancy-best-practices
:page-description: Multi-tenancy is achieved in ThoughtSpot via group configuration

There are many situations where ThoughtSpot must be configured for multi-tenancy. With ThoughtSpot Everywhere, almost every deployment involves an application developer providing content to many distinct organizations. A ThoughtSpot Enterprise deployment may require separation between departments within the larger company. In both cases, the techniques in this article for creating separation of users and content will apply.

== What is multi-tenancy?
Multi-tenancy describes a single software system serving users from many distinct organizations, who cannot have awareness of one another or access to each other’s content.

Within this section, a "multi-tenanted" system is one where an administrator see everything at once from a single login, while a "single-tenanted" system does have an “all content” view available, even to an administrator account.

== Multi-tenancy in ThoughtSpot is achieved using groups
ThoughtSpot groups are the best mechanism for all access control and security within ThoughtSpot. Groups serve the purpose of folders, roles, and row-level security assignment in ThoughtSpot. When configured correctly, users from one organization never see content, groups or other users from different organizations.

Because search is the primary organization method within ThoughtSpot and group membership is the mechanism for access control, when viewing the server as an administrator, all of the users, groups and content will be available and the multi-tenanted nature presented to the individual users may not be obvious at a glance.

Creating and auditing the groups, group membership and the sharing settings is best accomplished via the xref:rest-api-reference.adoc[REST API]. All settings and configurations are available through the ThoughtSpot UI, but we expect synchronization with the web application using the REST APIs at a production level.

== Types of multi-tenancy in ThoughtSpot
Because ThoughtSpot has its own users, groups, and data objects, and connects to cloud data warehouses that have their own set of objects, there are two separate but interacting forms of multi-tenancy to set up correctly:

* Multi-tenancy at the ThoughtSpot user level: Each instance of ThoughtSpot has users, who belong to various groups. When configured correctly, groups control what sets of users see and who they can share with.
* Multi-tenancy at the data level: ThoughtSpot connects to cloud data warehouses (CDW) to retrieve data. CDWs can be configured as multi-tenant or single-tenant.

There are two aspects of groups which interact to create the “wall” between customer organizations: “shared content” and “non-shareable groups”.

== Multi-tenancy at the user level
Each group and user has a "sharing visibility" property, which can be set to *SHAREABLE* or *NOT SHAREABLE*.

When a group is *NOT SHAREABLE*, the users within that group cannot share to that group or to other users in that group.

*NOT SHAREABLE* groups provide access to content (or privileges) without breaking user separation. Each user has no concept they belong to the group - they simply have access to the content.

When a user is set to *SHAREABLE*, other users within the same *SHAREABLE* group as that user can share content to them individually.

An administrator account can share to any group, regardless of the shareable property, while regular users can only share to those groups they belong to that are set to *SHAREABLE*, and *SHAREABLE* users within those groups.

To allow for multi-tenanted self-service, *SHAREABLE* groups can be created for each organization, so that only the users of each organization can share with one another. The choice of whether to make users shareable or not is up to you - if you prefer all sharing to be done at the group level, then you can set all users to *NOT SHAREABLE*.

[NOTE]
====
Avoid using the same group for access control and other privileges. Because a user can share with anyone in a group they belong to, they can potentially share restricted data.
====

== Multi-Tenancy at the Data Level
We will call a database multi-tenanted when a single set of credentials can see all of the data for all customer organizations. In a multi-tenanted database, there is typically a column named “customer_id” or “tenant_id” on every row of data within the database - we’ll call it the tenant key. Filtering against this tenant key splits the data for each customer organization.

If the rules of multi-tenancy are more complex than a simple tenant key on each row of data, there should at least be one table which defines the tenants and can be joined in a way to filter the other tables appropriately.

If the cloud data warehouse you are connecting to is multi-tenanted as described above, then you will only need one set of data objects in ThoughtSpot. The tables will be configured with row-level security (RLS), so that every query will filter against the tenant key in the database.

If there is a separate database connection for each customer organization, then the database pattern is single-tenant, and you will need to create objects for each tenant. ThoughtSpot provides APIs and the TML document language for automating the creation / deployment of each tenant’s objects.

=== Access controls on content
ThoughtSpot controls content access through the concept of sharing. Content in ThoughtSpot belongs to its creator (owner), and by default they are the only user who knows the content exists. This allows for self-service creation of new searches and pinboards.

A user only sees content when it is:

* **Shared** directly with the **user**
* **Shared** with a **group** the user belongs to
* **Created** or **owned** by the user

When content is shared to a group, all of the members of that group will have access to the content.

=== What content should be shared?
While you can share individual tables from connections to users, the best practice is to create link:https://cloud-docs.thoughtspot.com/admin/ts-cloud/worksheet-create.html[worksheets, window=_blank] and only share the relevant worksheets to end users. Any pinboards and saved answers shared to users should only connect to worksheets.

Remember to share the worksheet as *READ_ONLY* along with the pinboards and answers so the users can access self-service features such as changing filter values.


=== Row level security (RLS) groups
Row level security filters the results of database queries to only show a user the data they should have access to.

Row level security rules  in ThoughtSpot use the username or the group names of the groups the user belongs to as part of all queries.

Row level security groups should be created separately from content access groups, because the row level security group must have a name that matches the values in the tenant key column in the database.

Row level security groups should be set to Not Shareable - this way you know that content sharing only occurs via the content access groups. It is much simpler to audit

Row level security can be considerably more complex than just splitting at the tenant level and ThoughtSpot does facilitate these more complex models (guide to security). However, the basics of RLS to split at the tenant key level are always present and require the creation of the RLS groups.
